language: go

# safelist
branches:
  only:
  - try_specify_event_in_yaml

go:
- master

before_install:
  - go get -t -v ./...

script: go test -cover -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

